### ISSUE TITLE
Inquiry About API Transaction and Facial Recognition for Transfers

### ISSUE THREAD

**Issue by a23232390** [CookieGMVN/MBBank#22]
I would like to know if your API supports transaction functions. Additionally, is facial recognition required for conducting transfer operations?

Thank you for your response.

**Comment by CookieGMVN** [comment]
@a23232390 Hi there, I'm Cookie, and I'm here to answer your question:
My library is not supported for making transactions (and will not in the future), because MB's web transaction system is too complex and is not necessary to make one. Of course, you need to verify your biometrics before making transaction, and it's required for transaction that is more than 10 million VND in value.
Hope this reply helps you.

**Comment by a23232390** [comment]
@CookieGMVN  thank

I would like to ask about my client needing to manage multiple accounts. Do you know if the current biometric information systems only use facial recognition, or can other biometric information be used? Also, what is the difference between 3D and 2D recognition?

**Comment by CookieGMVN** [comment]
@a23232390 Hi there,
Multiple accounts is supported, but you need to customize some parts of this library to get it works perfectly. The biometric information systems used by banks in Vietnam only use facial recognition, since it's easy to collect just by a camera. By the way, the facial recognition used by banks only use 2D recognition with liveliness recognition (by recording a video and force you to move your head).

**Comment by a23232390** [comment]
@CookieGMVN  Thank you so much for helping me understand the complete recognition process.

**Comment by a23232390** [comment]
@CookieGMVN   hi 

Does facial recognition only use 2D recognition with liveness detection (by recording a video and forcing you to move your head) Do you know what specific movements are required?

**Comment by CookieGMVN** [comment]
@a23232390 Hi there,
Unfortunately, I don't know what exact movements are required. Hope this helps you.

**Comment by a23232390** [comment]
@CookieGMVN   ok  Thank you so much for helping me ~~~
